const BATTERIES = [
  {
    id: 1,
    name: 'Amaron Pro Bike Rider',
    model: 'AP-PRO 35B24L',
    type: 'bike',
    badge: 'Best Seller',
    emoji: '🔋',
    capacity: '35 Ah',
    warranty: '48 Months',
    stock: 12,
    rating: 4.8,
    reviews: 234,
    price: 2499,
    features: ['Maintenance Free', 'High CCA', 'Vibration Resistant', 'Fast Charge'],
  },
  {
    id: 2,
    name: 'Amaron Black Car Battery',
    model: 'BL-550D23L',
    type: 'car',
    badge: 'Premium',
    emoji: '🚗',
    capacity: '55 Ah',
    warranty: '60 Months',
    stock: 8,
    rating: 4.9,
    reviews: 412,
    price: 5999,
    features: ['Silver-Calcium Alloy', 'Low Self Discharge', 'Enhanced Cranking', 'BIS Certified'],
  },
  {
    id: 3,
    name: 'Amaron FreshBlock',
    model: 'FB-950D31L',
    type: 'car',
    badge: 'New',
    emoji: '⚡',
    capacity: '95 Ah',
    warranty: '72 Months',
    stock: 5,
    rating: 4.7,
    reviews: 89,
    price: 8999,
    features: ['Max Life Technology', 'High Reserve Capacity', 'Zero Maintenance', 'Premium Build'],
  },
  {
    id: 4,
    name: 'Amaron Hi-Life Bike',
    model: 'HL-BIK-00042B20L',
    type: 'bike',
    badge: 'Popular',
    emoji: '🏍️',
    capacity: '42 Ah',
    warranty: '36 Months',
    stock: 20,
    rating: 4.6,
    reviews: 176,
    price: 1899,
    features: ['Sealed Maintenance Free', 'Spill Proof', 'Long Life', 'Quick Charge'],
  },
  {
    id: 5,
    name: 'Amaron GO Car Battery',
    model: 'GO-545D18L',
    type: 'car',
    badge: 'Value Pick',
    emoji: '🔆',
    capacity: '45 Ah',
    warranty: '48 Months',
    stock: 15,
    rating: 4.5,
    reviews: 298,
    price: 4299,
    features: ['Silver Calcium', 'Improved Life', 'Wide Range', 'BIS Approved'],
  },
  {
    id: 6,
    name: 'Amaron Flo Car Battery',
    model: 'FL-600D26L',
    type: 'car',
    badge: 'Premium',
    emoji: '💎',
    capacity: '60 Ah',
    warranty: '66 Months',
    stock: 7,
    rating: 4.8,
    reviews: 154,
    price: 7499,
    features: ['Flo Technology', 'Max Reservoirs', 'Extreme Temperature', 'Longer Life'],
  },
];

const COMPATIBILITY = {
  bike: {
    Honda:   { 'Activa 6G': 1, 'CB Shine': 1, 'Unicorn': 4 },
    Bajaj:   { 'Pulsar 150': 1, 'Pulsar NS200': 4, 'Platina': 1 },
    TVS:     { 'Apache RTR 160': 4, 'Jupiter': 1, 'NTorq 125': 1 },
    Hero:    { 'Splendor Plus': 1, 'HF Deluxe': 1, 'Xtreme 160R': 4 },
    Yamaha:  { 'FZ-S V3': 4, 'R15 V4': 4, 'Fascino 125': 1 },
    Royal_Enfield: { 'Classic 350': 4, 'Meteor 350': 4, 'Hunter 350': 4 },
  },
  car: {
    Maruti:  { 'Swift Petrol': 5, 'Swift Diesel': 2, 'Baleno': 5, 'Dzire': 5 },
    Hyundai: { 'Creta Petrol': 5, 'Creta Diesel': 6, 'i20': 5 },
    Tata:    { 'Nexon Petrol': 5, 'Nexon Diesel': 6, 'Tiago': 5 },
    Mahindra: { 'XUV500': 6, 'Scorpio': 6, 'XUV300': 5 },
    Toyota:  { 'Fortuner': 6, 'Innova': 6, 'Glanza': 5 },
    Kia:     { 'Seltos': 5, 'Sonet': 5 },
  },
};

module.exports = { BATTERIES, COMPATIBILITY };
